AWSTemplateFormatVersion: '2010-09-09'
Description: Configure ES Old Log Deletion
Parameters:
  S3BucketName:
    Type: String
    Default: 'lambda-code'
    Description: Lambda Code zip file S3 bucket name
  S3FileName:
    Type: String
    Default: 'delete-old-logs-development.zip'
    Description: Lambda Code zip filename in S3
  CronExpression:
    Type: String
    Default: '0 0 * * ? *'
    Description: Cron Expression for the rule
  Environment:
    Type: String
    Default: 'development'
    Description: Environment name
  LabmdaRoleArn:
    Type: String
    Description: Lambda Role Arn
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Configurations
        Parameters:
          - S3BucketName
          - S3FileName
          - CronExpression
          - Environment
          - LabmdaRoleArn
Resources:
  DeleteOldLogs:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: nodejs12.x
      Role: !Ref LabmdaRoleArn
      Handler: index.handler
      MemorySize: 1024
      Timeout: 300
      Code:
        S3Bucket: !Sub ${S3BucketName}
        S3Key: !Sub ${S3FileName}
      Description: Invoke a function during stack creation.
  CWRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Delete old indices'
      ScheduleExpression: !Sub 'cron(${CronExpression})'
      State: 'ENABLED'
      Targets:
        - Id: !Sub 'DelOldLogs-${Environment}'
          Arn: !Ref LabmdaRoleArn
