AWSTemplateFormatVersion: 2010-09-09
Description: Create Log publish resources
Parameters:
  EnvironmentName:
    Type: String
    Default: 'development'
    Description: Name Of The Environment
  ESClusterDomainEP:
    Type: String
    Description: ES Cluster Domain Endpoint
  ClusterName:
    Type: String
    Default: 'dev-eks'
    Description: Name Of The EKS Cluster
  S3BucketName:
    Type: String
    Default: 'lambda-code'
    Description: Lambda Code zip file S3 bucket name
  S3FileName:
    Type: String
    Default: 'logstoes-development.zip'
    Description: Lambda Code zip filename in S3
  LabmdaRoleArn:
    Type: String
    Description: Lambda Role Arn
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Configurations
        Parameters:
          - EnvironmentName
          - ESClusterDomainEP
          - ClusterName
          - S3BucketName
          - S3FileName
          - LabmdaRoleArn
Resources:
  LogsToElasticsearch:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub 'LogsToElasticsearch-${EnvironmentName}-${ClusterName}'
      Runtime: nodejs12.x
      Role: !Ref LabmdaRoleArn
      Handler: index.handler
      Environment:
        Variables:
          elasticsearch_cluster_dns: !Ref ESClusterDomainEP
          environment_name: !Ref EnvironmentName
      Code:
        S3Bucket: !Sub ${S3BucketName}
        S3Key: !Sub ${S3FileName}
      Description: Invoke a function during stack creation.
  CloudWatchSubscriptionFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
          - "LogsToElasticsearch"
          - "Arn"
      Action: 'lambda:InvokeFunction'
      Principal: !Sub 'logs.${AWS::Region}.amazonaws.com'
      SourceArn: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/${EnvironmentName}/eks/${ClusterName}/containers:*'
  SubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn: CloudWatchSubscriptionFunctionPermission
    Properties:
      LogGroupName: !Sub '/${EnvironmentName}/eks/${ClusterName}/containers'
      FilterPattern: ""
      DestinationArn:
        Fn::GetAtt:
          - "LogsToElasticsearch"
          - "Arn"
