AWSTemplateFormatVersion: '2010-09-09'
Description: Configure ES Log rollover
Parameters:
  S3BucketName:
    Type: String
    Default: 'lambda-code'
    Description: Lambda Code zip file S3 bucket name
  S3FileName:
    Type: String
    Default: 'rollover.zip'
    Description: Lambda Code zip filename in S3
  LabmdaRoleArn:
    Type: String
    Description: Lambda Role Arn
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Configurations
        Parameters:
          - S3BucketName
          - S3FileName
          - LabmdaRoleArn
Resources:
  LogsRollover:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: nodejs12.x
      Role: !Ref LabmdaRoleArn
      Handler: index.handler
      MemorySize: 1024
      Timeout: 300
      Code:
        S3Bucket: !Sub ${S3BucketName}
        S3Key: !Sub ${S3FileName}
      Description: Invoke a function during stack creation.
  CloudWatchLogRolloverRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Rollover Log indices'
      ScheduleExpression: 'cron(0 0 * * ? *)'
      State: 'ENABLED'
      Targets:
        - Id: 'Rollover-Lambda-Function'
          Arn: !Ref LabmdaRoleArn
