AWSTemplateFormatVersion: '2010-09-09'
Description: Configure ES Log rollover
Parameters:
  S3BucketName:
    Type: String
    Default: 'lambda-code'
    Description: Lambda Code zip file S3 bucket name
  S3FileName:
    Type: String
    Default: 'rollover.zip'
    Description: Lambda Code zip filename in S3
  ESClusterDomainEP:
    Type: String
    Description: ES Cluster Domain Endpoint
  EnvironmentName:
    Type: String
    Default: 'development'
    Description: Environment Name
  CronExpression:
    Type: String
    Default: '0 0 * * ? *'
    Description: Cron Expression for the rule
  LabmdaRoleArn:
    Type: String
    Description: Lambda Role Arn
  MemorySizeMB:
    Type: Number
    Default: 1024
    Description: Lambda max MemorySize in MB
  LambdaTimeoutSeconds:
    Type: Number
    Default: 900
    Description: Lambda timeout value
  SnapshotsReplication:
    Type: String
    AllowedValues:
      - 'Required'
      - 'Not Required'
    Default: Not Required
    Description: Mention is Snapshots Required

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Configurations
        Parameters:
          - S3BucketName
          - S3FileName
          - CronExpression
          - LabmdaRoleArn
          - ESClusterDomainEP
          - EnvironmentName
          - MemorySizeMB
          - LambdaTimeoutSeconds
          - SnapshotsReplication

Conditions:
  HasSnapshotsReplication: !Equals
    - !Ref SnapshotsReplication
    - 'Required'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Condition: HasSnapshotsReplication
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: 'true'
        BlockPublicPolicy: 'true'
        IgnorePublicAcls: 'true'
        RestrictPublicBuckets: 'true'
      Tags:
        - Key: "Name"
          Value: !Sub "${EnvironmentName}-es-index-snapshot-repository"

  S3ArchiveRole:
    Type: 'AWS::IAM::Role'
    Condition: HasSnapshotsReplication
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - es.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /

  SnapshotPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: HasSnapshotsReplication
    Properties:
      Path: /
      Roles:
        - Ref: S3ArchiveRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:ListBucket
          - s3:GetObject
          - s3:PutObject
          - s3:DeleteObject
          Resource:
            Fn::Join:
              - ""
              -
                - "arn:aws:s3:::"
                - !Ref S3Bucket
                - "/*"

  LogsRollover:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: nodejs12.x
      Role: !Ref LabmdaRoleArn
      Handler: index.handler
      Environment:
        Variables:
          elasticsearch_cluster_dns: !Ref ESClusterDomainEP
          environment_name: !Ref EnvironmentName
          is_snapshots_enabled: !If
            - HasSnapshotsReplication
            - true
            - false
          snapshot_bucket_name: !If
            - HasSnapshotsReplication
            - !Ref S3Bucket
            - !Ref AWS::NoValue
          snapshot_role_name: !If
            - HasSnapshotsReplication
            - !GetAtt S3ArchiveRole.Arn
            - !Ref AWS::NoValue
      MemorySize: !Ref MemorySizeMB
      Timeout: !Ref LambdaTimeoutSeconds
      Code:
        S3Bucket: !Sub ${S3BucketName}
        S3Key: !Sub ${S3FileName}
      Description: Invoke a function during stack creation.

  CloudWatchSubscriptionFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
          - "LogsRollover"
          - "Arn"
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn:
        Fn::GetAtt:
          - "CloudWatchLogRolloverRule"
          - "Arn"

  CloudWatchLogRolloverRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Rollover Log indices'
      ScheduleExpression: !Sub 'cron(${CronExpression})'
      State: 'ENABLED'
      Targets:
        - Id: 'Rollover-logs-daily'
          Arn:
            Fn::GetAtt:
              - "LogsRollover"
              - "Arn"
